Juan/JuanApp/Controllers/BasketController.cs
using Newtonsoft.Json;

namespace JuanApp.Controllers;
public class BasketController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserManager<AppUser> _userManager;
    public BasketController(AppDbContext context, UserManager<AppUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public async Task<IActionResult> Index()
    {
        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];
        if (!string.IsNullOrWhiteSpace(basket)) basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);

        foreach (BasketVM basketVM in basketVMs)
        {
            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id);
            basketVM.Title = product.Title;
            basketVM.Image = product.MainImage;
            basketVM.Price = product.Price * (100 - product.Discount) / 100;
        }

        return View(basketVMs);
    }

    public async Task<IActionResult> AddBasket(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");
        if (!await _context.Products.AnyAsync(p => !p.IsDeleted && p.Id == id)) return NotFound("Id is incorrect.");

        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];

        if (!string.IsNullOrWhiteSpace(basket))
        {
            basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            if (basketVMs.Exists(b => b.Id == id))
            {
                Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);
                if (basketVMs.Find(b => b.Id == id).Count < product.Count) basketVMs.Find(b => b.Id == id).Count += 1;
            }
            else basketVMs.Add(new BasketVM { Id = (int)id, Count = 1 });
        }
        else basketVMs.Add(new BasketVM { Id = (int)id, Count = 1 });

        Response.Cookies.Append("basket", JsonConvert.SerializeObject(basketVMs));

        if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
        {
            AppUser? appUser = await _userManager.Users.Include(u => u.BasketProducts.Where(b => !b.IsDeleted))
                .FirstOrDefaultAsync(u =>  u.UserName == User.Identity.Name);

            if (appUser.BasketProducts != null && appUser.BasketProducts.Any())
            {
                BasketProduct userBasketProduct = appUser.BasketProducts.FirstOrDefault(bp => bp.ProductId == id);
                if (userBasketProduct != null) userBasketProduct.Count = basketVMs.FirstOrDefault(b => b.Id == id).Count;
                else
                {
                    userBasketProduct = new()
                    {
                        UserId = appUser.Id,
                        ProductId = id,
                        Count = basketVMs.FirstOrDefault(b => b.Id == id).Count
                    };

                    await _context.BasketProducts.AddAsync(userBasketProduct);
                }
            }
            else
            {
                BasketProduct userBasketProduct = new()
                {
                    UserId = appUser.Id,
                    ProductId = id,
                    Count = basketVMs.FirstOrDefault(b => b.Id == id).Count
                };

                await _context.BasketProducts.AddAsync(userBasketProduct);
            }

            await _context.SaveChangesAsync();
        }

        foreach (BasketVM basketVM in basketVMs)
        {
            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id);
            basketVM.Title = product.Title;
            basketVM.Image = product.MainImage;
            basketVM.Price = product.Price * (100 - product.Discount) / 100;
        }

        return PartialView("_BasketPartial", basketVMs);
    }

    public async Task<IActionResult> RemoveBasket(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");

        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];

        if (!string.IsNullOrWhiteSpace(basket))
        {
            basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            if (!basketVMs.Remove(basketVMs.Find(b => b.Id == id))) return NotFound("Id is incorrect.");
        }
        else return BadRequest("Basket does not exist.");

        Response.Cookies.Append("basket", JsonConvert.SerializeObject(basketVMs));

        if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
        {
            AppUser? appUser = await _userManager.Users.Include(u => u.BasketProducts.Where(b => !b.IsDeleted))
                .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (appUser.BasketProducts != null && appUser.BasketProducts.Any())
            {
                BasketProduct userBasketProduct = appUser.BasketProducts.FirstOrDefault(bp => bp.ProductId == id);
                if (userBasketProduct != null)
                {
                    userBasketProduct.IsDeleted = true;
                    userBasketProduct.DeletedBy = appUser.UserName;
                    userBasketProduct.DeletedDate = DateTime.UtcNow.AddHours(4);

                    await _context.SaveChangesAsync();
                }
            }
        }

        foreach (BasketVM basketVM in basketVMs)
        {
            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id);
            basketVM.Title = product.Title;
            basketVM.Image = product.MainImage;
            basketVM.Price = product.Price * (100 - product.Discount) / 100;
        }

        return PartialView("_BasketPartial", basketVMs);
    }

    public async Task<IActionResult> CountInc(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");

        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];

        if (!string.IsNullOrWhiteSpace(basket))
        {
            basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            if (basketVMs.Exists(b => b.Id == id))
            {
                Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);
                BasketVM basketVM = basketVMs.Find(b => b.Id == id);
                basketVM.Count = basketVM.Count <= product.Count ? basketVM.Count + 1 : product.Count;
            }
            else return NotFound("Id is incorrect.");
        }
        else return BadRequest("Basket does not exist.");

        Response.Cookies.Append("basket", JsonConvert.SerializeObject(basketVMs));

        if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
        {
            AppUser? appUser = await _userManager.Users.Include(u => u.BasketProducts.Where(b => !b.IsDeleted))
                .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (appUser.BasketProducts != null && appUser.BasketProducts.Any())
            {
                BasketProduct userBasketProduct = appUser.BasketProducts.FirstOrDefault(bp => bp.ProductId == id);
                if (userBasketProduct != null) userBasketProduct.Count = basketVMs.FirstOrDefault(b => b.Id == id).Count;
                else
                {
                    userBasketProduct = new()
                    {
                        UserId = appUser.Id,
                        ProductId = id,
                        Count = basketVMs.FirstOrDefault(b => b.Id == id).Count
                    };

                    await _context.BasketProducts.AddAsync(userBasketProduct);
                }
            }
            else
            {
                BasketProduct userBasketProduct = new()
                {
                    UserId = appUser.Id,
                    ProductId = id,
                    Count = basketVMs.FirstOrDefault(b => b.Id == id).Count
                };

                await _context.BasketProducts.AddAsync(userBasketProduct);
            }

            await _context.SaveChangesAsync();
        }


        foreach (BasketVM basketVM in basketVMs)
        {
            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id);
            basketVM.Title = product.Title;
            basketVM.Image = product.MainImage;
            basketVM.Price = product.Price * (100 - product.Discount) / 100;
        }

        return PartialView("_BasketPartial", basketVMs);
    }

    public async Task<IActionResult> CountDec(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");

        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];

        if (!string.IsNullOrWhiteSpace(basket))
        {
            basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            if (basketVMs.Exists(b => b.Id == id))
            {
                Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);
                BasketVM basketVM = basketVMs.Find(b => b.Id == id);
                basketVM.Count = basketVM.Count > 1 ? basketVM.Count - 1 : 1;
            }
            else return NotFound("Id is incorrect.");
        }
        else return BadRequest("Basket does not exist.");

        Response.Cookies.Append("basket", JsonConvert.SerializeObject(basketVMs));

        if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
        {
            AppUser? appUser = await _userManager.Users.Include(u => u.BasketProducts.Where(b => !b.IsDeleted))
                .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (appUser.BasketProducts != null && appUser.BasketProducts.Any())
            {
                BasketProduct userBasketProduct = appUser.BasketProducts.FirstOrDefault(bp => bp.ProductId == id);
                if (userBasketProduct != null) userBasketProduct.Count = basketVMs.FirstOrDefault(b => b.Id == id).Count;
                else

Juan/JuanApp/Controllers/OrderController.cs
namespace JuanApp.Controllers;
[Authorize(Roles ="Member")]
public class OrderController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserManager<AppUser> _userManager;
    public OrderController(AppDbContext context, UserManager<AppUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }
    
    public async Task<IActionResult> CheckOut()
    {
        AppUser? appUser = await _userManager.Users
            .Include(u => u.Addresses.Where(a => !a.IsDeleted && a.IsDefault))
            .Include(u => u.BasketProducts.Where(bp => !bp.IsDeleted)).ThenInclude(bp => bp.Product)
            .FirstOrDefaultAsync(u => u.NormalizedUserName == User.Identity.Name.Trim().ToUpperInvariant());

        if (appUser.BasketProducts == null || !appUser.BasketProducts.Any())
        {
            TempData["Info"] = "Please add products to your basket first.";
            return RedirectToAction("Index", "Product");
        }

        OrderVM orderVM = new()
        {
            Order = new()
            {
                Name = appUser.Name,
                Surname = appUser.Surname,
                Email = appUser.Email,
                Country = appUser.Addresses.First().Country,
                TownCity = appUser.Addresses.First().TownCity,
                Line1 = appUser.Addresses.First().Line1,
                Line2 = appUser.Addresses.First().Line2,
                ZipCode = appUser.Addresses.First().ZipCode
            },
            BasketVMs = appUser.BasketProducts.Select(x => new BasketVM
            {
                Id = (int)x.ProductId,
                Count = x.Count,
                Image = x.Product.MainImage,
                Title = x.Product.Title,
                Price = x.Product.Price * (100 - x.Product.Discount) / 100
            }).ToList()
        };

        return View(orderVM);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> CheckOut(Order order)
    {
        AppUser? appUser = await _userManager.Users
            .Include(u => u.Addresses.Where(a => !a.IsDeleted && a.IsDefault)).Include(u => u.Orders)
            .Include(u => u.BasketProducts.Where(bp => !bp.IsDeleted)).ThenInclude(bp => bp.Product)
            .FirstOrDefaultAsync(u => u.NormalizedUserName == User.Identity.Name.Trim().ToUpperInvariant());

        OrderVM orderVM = new()
        {
            Order = order,
            BasketVMs = appUser.BasketProducts.Select(x => new BasketVM
            {
                Id = (int)x.ProductId,
                Count = x.Count,
                Image = x.Product.MainImage,
                Title = x.Product.Title,
                Price = x.Product.Price * (100 - x.Product.Discount) / 100
            }).ToList()
        };

        if (!ModelState.IsValid) return View(orderVM);
        
        if (appUser.BasketProducts == null || !appUser.BasketProducts.Any())
        {
            TempData["Info"] = "Please add products to your basket first.";
            return RedirectToAction("Index", "Product");
        }

        List<OrderProduct> orderProducts = new();

        foreach (BasketProduct basketProduct in appUser.BasketProducts)
        {
            basketProduct.IsDeleted = true;
            basketProduct.DeletedBy = appUser.UserName;
            basketProduct.DeletedDate = DateTime.UtcNow.AddHours(4);
            orderProducts.Add(new()
            {
                Title = basketProduct.Product.Title,
                Price = basketProduct.Product.Price * (100 - basketProduct.Product.Discount) / 100,
                Count = basketProduct.Count,
                CreatedBy = appUser.UserName
            });
        }

        order.Status = 1;
        order.UserId = appUser.Id;
        order.CreatedBy = appUser.UserName;
        order.OrderProducts = orderProducts;
        order.No = appUser.Orders != null && appUser.Orders.Any() ? appUser.Orders
            .OrderByDescending(o => o.Id).FirstOrDefault().No + 1 : 1;

        Response.Cookies.Append("basket", "");

        await _context.Orders.AddAsync(order);
        await _context.SaveChangesAsync();

        TempData["Success"] = "Your order has been placed successfully!";

        return RedirectToAction("Index", "Product");
    }
}

Juan/JuanApp/Views/Shared/_BasketPagePartial.cshtml
@model IEnumerable<BasketVM>

<div class="row">
    <div class="col-lg-12">
        <div class="cart-table table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th class="pro-thumbnail">Thumbnail</th>
                        <th class="pro-title">Product</th>
                        <th class="pro-price">Price</th>
                        <th class="pro-quantity">Quantity</th>
                        <th class="pro-subtotal">Total</th>
                        <th class="pro-remove">Remove</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (BasketVM basketVM in Model)
                    {
                        <tr>
                            <td class="pro-thumbnail">
                                <a asp-controller="Product" asp-action="Details" asp-route-id="@basketVM.Id">
                                    <img class="img-fluid" src="~/assets/img/product/@basketVM.Image" alt="Product" />
                                </a>
                            </td>
                            <td class="pro-title">
                                <a asp-controller="Product" asp-action="Details" asp-route-id="@basketVM.Id">@basketVM.Title</a>
                            </td>
                            <td class="pro-price"><span>$@(basketVM.Price.ToString("0.00"))</span></td>
                            <td class="quantity">
                                <div class="pro-qty">
                                    <span class="qtybtn">-</span>
                                    <input data-id="@basketVM.Id" value="@basketVM.Count" readonly />
                                    <span class="inc qtybtn">+</span>
                                </div>
                            </td>
                            <td class="pro-subtotal"><span>@((basketVM.Price * basketVM.Count).ToString("0.00"))</span></td>
                            <td class="pro-remove">
                                <a class="minicart-remove" asp-controller="Basket" asp-action="RemoveBasket" asp-route-id="@basketVM.Id">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-5 ml-auto">
        <div class="cart-calculator-wrapper">
            <div class="cart-calculate-items">
                <h3>Cart Totals</h3>
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <td>Sub Total</td>
                            <td>$@Model.Sum(b => b.Price * b.Count).ToString("0.00")</td>
                        </tr>
                        <tr>
                            <td>VAT (20 %)</td>
                            <td>$@Model.Sum(b => b.Price * b.Count * 0.2).ToString("0.00")</td>
                        </tr>
                        <tr class="total">
                            <td>Total</td>
                            <td class ="total-amount">$@Model.Sum(b => b.Price * b.Count * 1.2).ToString("0.00")</td>
                        </tr>
                    </table>
                </div>
            </div>
            <a asp-controller="Order" asp-action="CheckOut" class="btn d-block">Proceed Checkout</a>
        </div>
    </div>
</div>

Juan/JuanApp/Views/Shared/_BasketPartial.cshtml
@model IEnumerable<BasketVM>

<div class="minicart-item-wrapper">
    <ul>
        @foreach (BasketVM basketVM in Model)
        {
            <li class="minicart-item">
                <div class="minicart-thumb">
                    <a asp-controller="Product" asp-action="Details" asp-route-id="@basketVM.Id"><img src="~/assets/img/product/@basketVM.Image" alt="product"></a>
                </div>
                <div class="minicart-content">
                    <h3 class="product-name"><a asp-controller="Product" asp-action="Details" asp-route-id="@basketVM.Id">@basketVM.Title</a></h3>
                    <p>
                        <span class="cart-quantity">@basketVM.Count <strong>&times;</strong></span>
                        <span class="cart-price">$@basketVM.Price.ToString("0.00")</span>
                    </p>
                </div>
                <a asp-controller="Basket" asp-action="RemoveBasket" asp-route-id="@basketVM.Id" class="minicart-remove"><i class="ion-android-close"></i></a>
            </li>
        }
    </ul>
</div>
<div class="minicart-pricing-box">
    <ul>
        <li>
            <span>sub-total</span>
            <span><strong>$@Model.Sum(b => b.Price * b.Count).ToString("0.00")</strong></span>
        </li>
        <li>
            <span>VAT (20%)</span>
            <span><strong>$@Model.Sum(b => b.Price * b.Count * 0.2).ToString("0.00")</strong></span>
        </li>
        <li class="total">
            <span>total</span>
            <span><strong>$@Model.Sum(b => b.Price * b.Count * 1.2).ToString("0.00")</strong></span>
        </li>
    </ul>
</div>
<div class="minicart-button">
    <a asp-controller="Basket" asp-action="Index"><i class="fa fa-shopping-cart"></i> view cart</a>
    @if (Model.Count() > 0)
    {
        <a asp-controller="Order" asp-action="CheckOut"><i class="fa fa-share"></i> checkout</a>
    }
</div>

Juan/JuanApp/Views/Shared/_LoadMorePartial.cshtml
@model IEnumerable<Product>

@foreach (Product product in Model)
{
    <div class="col-lg-4 col-sm-6">
        <!-- product grid item start -->
        <div class="product-item mb-53">
            <div class="product-thumb">
                <a asp-controller="Product" asp-action="Details" asp-route-id="">
                    <img src="~/assets/img/product/product-1.jpg" alt="">
                </a>
            </div>
            <div class="product-content">
                <h5 class="product-name">
                    <a asp-controller="Product" asp-action="Details" asp-route-id="">Leather Mens Slipper</a>
                </h5>
                <div class="price-box">
                    @if (product.Discount > 0)
                    {
                        <span class="price-regular">$@((product.Price - product.Price * product.Discount / 100).ToString("#.##"))</span>
                        <span class="price-old"><del>$@product.Price.ToString("#.##")</del></span>
                    }
                    else { <span class="price-regular">$@product.Price.ToString("#.##")</span> }
                </div>
                <div class="product-action-link">
                    <a href="#" data-toggle="tooltip" title="Wishlist"><i class="ion-android-favorite-outline"></i></a>
                    <a asp-controller="Basket" asp-action="AddBasket" asp-route-id="@product.Id" class="basket-btn" data-toggle="tooltip" title="Add To Cart"><i class="ion-bag"></i></a>
                    <a asp-controller="Product" asp-action="Modal" asp-route-id="@product.Id" class="modal-btn" data-toggle="modal" data-target="#quick_view">
                        <span data-toggle="tooltip" title="Quick View"><i class="ion-ios-eye-outline"></i></span>
                    </a>
                </div>
            </div>
        </div>
        <!-- product grid item end -->

        <!-- product list item start -->
        <div class="product-list-item mb-30">
            <div class="product-thumb">
                <a asp-controller="Product" asp-action="Details" asp-route-id="product.Id">
                    <img src="~/assets/img/product/@product.MainImage" alt="product thumb">
                </a>
            </div>
            <div class="product-content-list">
                <h5 class="product-name">
                    <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">@product.Title</a>
                </h5>
                <div class="price-box">
                    @if (product.Discount > 0)
                    {
                        <span class="price-regular">$@((product.Price - product.Price * product.Discount / 100).ToString("#.##"))</span>
                        <span class="price-old"><del>$@product.Price.ToString("#.##")</del></span>
                    }
                    else { <span class="price-regular">$@product.Price.ToString("#.##")</span> }
                </div>
                <p>@product.SmallDesc</p>
                <div class="product-link-2 position-static">
                    <a href="#" data-toggle="tooltip" title="Wishlist"><i class="ion-android-favorite-outline"></i></a>
                    <a asp-controller="Basket" asp-action="AddBasket" asp-route-id="@product.Id" class="basket-btn" data-toggle="tooltip" title="Add To Cart"><i class="ion-bag"></i></a>
                    <a asp-controller="Product" asp-action="Modal" asp-route-id="@product.Id" class="modal-btn" data-toggle="modal" data-target="#quick_view">
                        <span data-toggle="tooltip" title="Quick View"><i class="ion-ios-eye-outline"></i></span>
                    </a>
                </div>
            </div>
        </div>
        <!-- product list item start -->
    </div>
}

Juan/JuanApp/Views/Shared/_ModalPartial.cshtml
@model Product

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<div class="modal-body">
    <div class="product-details-inner">
        <div class="row">
            <div class="col-lg-5">
                <div class="product-large-slider mb-20">
                    @foreach (ProductImage productImage in Model.ProductImages)
                    {
                        <div class="pro-large-img img-zoom">
                            <img src="assets/img/product/@productImage.Image" alt="product thumb" />
                        </div>
                    }
                </div>
                <div class="pro-nav slick-row-5">
                    @foreach (ProductImage productImage in Model.ProductImages)
                    {
                        <div class="pro-nav-thumb"><img src="assets/img/product/@productImage.Image" alt="" /></div>
                    }
                </div>
            </div>
            <div class="col-lg-7">
                <div class="product-details-des">
                    <h3 class="pro-det-title">@Model.Title</h3>
                    <div class="pro-review">
                        <span><a href="#">1 Review(s)</a></span>
                    </div>
                    <div class="price-box">
                        @if (Model.Discount > 0)
                        {
                            <span class="price-regular">$@((Model.Price * (100 - Model.Discount) / 100).ToString("0.00"))</span>
                            <span class="price-old"><del>$@Model.Price.ToString("0.00")</del></span>
                        }
                        else { <span class="price-regular">$@Model.Price.ToString("0.00")</span> }
                    </div>
                    <p>@Model.SmallDesc</p>
                    <div class="quantity-cart-box d-flex align-items-center mb-20">
                        @if (Model.Count > 0)
                        {
                            <a asp-controller="Basket" asp-action="AddBasket" asp-route-id="@Model.Id"
                               class="btn btn-default basket-btn">Add To Cart</a>
                        }
                        else { <span class="btn btn-grey">Add To Cart</span> }
                    </div>
                    <div class="availability mb-20">
                        <h5 class="cat-title">Availability:</h5>
                        @if (Model.Count > 0) { <span>In Stock</span> }
                        else { <span class="text-danger">Stock Out</span> }
                    </div>
                    <div class="share-icon">
                        <h5 class="cat-title">Share:</h5>
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                        <a href="#"><i class="fa fa-google-plus"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

Juan/JuanApp/Views/Shared/_ProductsPartial.cshtml
@model IEnumerable<Product>

@foreach (Product product in Model)
{
    <div class="col-lg-4 col-sm-6">
        <!-- product grid item start -->
        <div class="product-item mb-53">
            <div class="product-thumb">
                <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">
                    <img src="~/assets/img/product/@product.MainImage" alt="">
                </a>
            </div>
            <div class="product-content">
                <h5 class="product-name">
                    <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">@product.Title</a>
                </h5>
                <div class="price-box">
                    @if (product.Discount > 0)
                    {
                        <span class="price-regular">$@((product.Price * (100 - product.Discount) / 100).ToString("0.00"))</span>
                        <span class="price-old"><del>$@product.Price.ToString("0.00")</del></span>
                    }
                    else { <span class="price-regular">$@product.Price.ToString("0.00")</span> }
                </div>
                <div class="product-action-link">
                    <a href="#" data-toggle="tooltip" title="Wishlist"><i class="ion-android-favorite-outline"></i></a>
                    <a asp-controller="Basket" asp-action="AddBasket" asp-route-id="@product.Id" class="basket-btn" data-toggle="tooltip" title="Add To Cart"><i class="ion-bag"></i></a>
                    <a asp-controller="Product" asp-action="Modal" asp-route-id="@product.Id" class="modal-btn" data-toggle="modal" data-target="#quick_view">
                        <span data-toggle="tooltip" title="Quick View"><i class="ion-ios-eye-outline"></i></span>
                    </a>
                </div>
            </div>
        </div>
        <!-- product grid item end -->

        <!-- product list item start -->
        <div class="product-list-item mb-30">
            <div class="product-thumb">
                <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">
                    <img src="~/assets/img/product/@product.MainImage" alt="product thumb">
                </a>
            </div>
            <div class="product-content-list">
                <h5 class="product-name">
                    <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">@product.Title</a>
                </h5>
                <div class="price-box">
                    @if (product.Discount > 0)
                    {
                        <span class="price-regular">$@((product.Price - product.Price * product.Discount / 100).ToString("0.00"))</span>
                        <span class="price-old"><del>$@product.Price.ToString("0.00")</del></span>
                    }
                    else { <span class="price-regular">$@product.Price.ToString("0.00")</span> }
                </div>
                <p>@product.SmallDesc</p>
                <div class="product-link-2 position-static">
                    <a href="#" data-toggle="tooltip" title="Wishlist"><i class="ion-android-favorite-outline"></i></a>
                    <a asp-controller="Basket" asp-action="AddBasket" asp-route-id="@product.Id" class="basket-btn" data-toggle="tooltip" title="Add To Cart"><i class="ion-bag"></i></a>
                    <a asp-controller="Product" asp-action="Modal" asp-route-id="@product.Id" class="modal-btn" data-toggle="modal" data-target="#quick_view">
                        <span data-toggle="tooltip" title="Quick View"><i class="ion-ios-eye-outline"></i></span>
                    </a>
                </div>
            </div>
        </div>
        <!-- product list item start -->
    </div>
}

Juan/JuanApp/Views/Shared/_SearchPartial.cshtml
@model IEnumerable<Product>
@foreach (Product product in Model)
{
    <li style="border:1px solid #dddddd; padding:0 20px;">
        <a href="#" class="d-flex justify-content-between align-items-center">
            <img style="width: 100px" src="/assets/images/product/@product.MainImage" />
            <p>@product.Title</p>
            <span class="price-sale">€@((product.Price * (100 - product.Discount) / 100).ToString("0.00"))</span>
        </a>
    </li>
}

Juan/JuanApp/Views/Shared/_ValidationPartial.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"
        integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js"
        integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>