Juan/JuanApp/Controllers/BasketController.cs
using Newtonsoft.Json;

namespace JuanApp.Controllers;
public class BasketController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserManager<AppUser> _userManager;
    public BasketController(AppDbContext context, UserManager<AppUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public async Task<IActionResult> Index()
    {
        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];
        if (!string.IsNullOrWhiteSpace(basket)) basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);

        foreach (BasketVM basketVM in basketVMs)
        {
            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id);
            basketVM.Title = product.Title;
            basketVM.Image = product.MainImage;
            basketVM.Price = product.Price * (100 - product.Discount) / 100;
        }

        return View(basketVMs);
    }

    public async Task<IActionResult> AddBasket(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");
        if (!await _context.Products.AnyAsync(p => !p.IsDeleted && p.Id == id)) return NotFound("Id is incorrect.");

        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];

        if (!string.IsNullOrWhiteSpace(basket))
        {
            basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            if (basketVMs.Exists(b => b.Id == id))
            {
                Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);
                if (basketVMs.Find(b => b.Id == id).Count < product.Count) basketVMs.Find(b => b.Id == id).Count += 1;
            }
            else basketVMs.Add(new BasketVM { Id = (int)id, Count = 1 });
        }
        else basketVMs.Add(new BasketVM { Id = (int)id, Count = 1 });

        Response.Cookies.Append("basket", JsonConvert.SerializeObject(basketVMs));

        if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
        {
            AppUser? appUser = await _userManager.Users.Include(u => u.BasketProducts.Where(b => !b.IsDeleted))
                .FirstOrDefaultAsync(u =>  u.UserName == User.Identity.Name);

            if (appUser.BasketProducts != null && appUser.BasketProducts.Any())
            {
                BasketProduct userBasketProduct = appUser.BasketProducts.FirstOrDefault(bp => bp.ProductId == id);
                if (userBasketProduct != null) userBasketProduct.Count = basketVMs.FirstOrDefault(b => b.Id == id).Count;
                else
                {
                    userBasketProduct = new()
                    {
                        UserId = appUser.Id,
                        ProductId = id,
                        Count = basketVMs.FirstOrDefault(b => b.Id == id).Count
                    };

                    await _context.BasketProducts.AddAsync(userBasketProduct);
                }
            }
            else
            {
                BasketProduct userBasketProduct = new()
                {
                    UserId = appUser.Id,
                    ProductId = id,
                    Count = basketVMs.FirstOrDefault(b => b.Id == id).Count
                };

                await _context.BasketProducts.AddAsync(userBasketProduct);
            }

            await _context.SaveChangesAsync();
        }

        foreach (BasketVM basketVM in basketVMs)
        {
            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id);
            basketVM.Title = product.Title;
            basketVM.Image = product.MainImage;
            basketVM.Price = product.Price * (100 - product.Discount) / 100;
        }

        return PartialView("_BasketPartial", basketVMs);
    }

    public async Task<IActionResult> RemoveBasket(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");

        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];

        if (!string.IsNullOrWhiteSpace(basket))
        {
            basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            if (!basketVMs.Remove(basketVMs.Find(b => b.Id == id))) return NotFound("Id is incorrect.");
        }
        else return BadRequest("Basket does not exist.");

        Response.Cookies.Append("basket", JsonConvert.SerializeObject(basketVMs));

        if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
        {
            AppUser? appUser = await _userManager.Users.Include(u => u.BasketProducts.Where(b => !b.IsDeleted))
                .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (appUser.BasketProducts != null && appUser.BasketProducts.Any())
            {
                BasketProduct userBasketProduct = appUser.BasketProducts.FirstOrDefault(bp => bp.ProductId == id);
                if (userBasketProduct != null)
                {
                    userBasketProduct.IsDeleted = true;
                    userBasketProduct.DeletedBy = appUser.UserName;
                    userBasketProduct.DeletedDate = DateTime.UtcNow.AddHours(4);

                    await _context.SaveChangesAsync();
                }
            }
        }

        foreach (BasketVM basketVM in basketVMs)
        {
            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id);
            basketVM.Title = product.Title;
            basketVM.Image = product.MainImage;
            basketVM.Price = product.Price * (100 - product.Discount) / 100;
        }

        return PartialView("_BasketPartial", basketVMs);
    }

    public async Task<IActionResult> CountInc(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");

        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];

        if (!string.IsNullOrWhiteSpace(basket))
        {
            basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            if (basketVMs.Exists(b => b.Id == id))
            {
                Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);
                BasketVM basketVM = basketVMs.Find(b => b.Id == id);
                basketVM.Count = basketVM.Count <= product.Count ? basketVM.Count + 1 : product.Count;
            }
            else return NotFound("Id is incorrect.");
        }
        else return BadRequest("Basket does not exist.");

        Response.Cookies.Append("basket", JsonConvert.SerializeObject(basketVMs));

        if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
        {
            AppUser? appUser = await _userManager.Users.Include(u => u.BasketProducts.Where(b => !b.IsDeleted))
                .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (appUser.BasketProducts != null && appUser.BasketProducts.Any())
            {
                BasketProduct userBasketProduct = appUser.BasketProducts.FirstOrDefault(bp => bp.ProductId == id);
                if (userBasketProduct != null) userBasketProduct.Count = basketVMs.FirstOrDefault(b => b.Id == id).Count;
                else
                {
                    userBasketProduct = new()
                    {
                        UserId = appUser.Id,
                        ProductId = id,
                        Count = basketVMs.FirstOrDefault(b => b.Id == id).Count
                    };

                    await _context.BasketProducts.AddAsync(userBasketProduct);
                }
            }
            else
            {
                BasketProduct userBasketProduct = new()
                {
                    UserId = appUser.Id,
                    ProductId = id,
                    Count = basketVMs.FirstOrDefault(b => b.Id == id).Count
                };

                await _context.BasketProducts.AddAsync(userBasketProduct);
            }

            await _context.SaveChangesAsync();
        }


        foreach (BasketVM basketVM in basketVMs)
        {
            Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id);
            basketVM.Title = product.Title;
            basketVM.Image = product.MainImage;
            basketVM.Price = product.Price * (100 - product.Discount) / 100;
        }

        return PartialView("_BasketPartial", basketVMs);
    }

    public async Task<IActionResult> CountDec(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");

        List<BasketVM> basketVMs = new();
        string? basket = Request.Cookies["basket"];

        if (!string.IsNullOrWhiteSpace(basket))
        {
            basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            if (basketVMs.Exists(b => b.Id == id))
            {
                Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == id);
                BasketVM basketVM = basketVMs.Find(b => b.Id == id);
                basketVM.Count = basketVM.Count > 1 ? basketVM.Count - 1 : 1;
            }
            else return NotFound("Id is incorrect.");
        }
        else return BadRequest("Basket does not exist.");

        Response.Cookies.Append("basket", JsonConvert.SerializeObject(basketVMs));

        if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
        {
            AppUser? appUser = await _userManager.Users.Include(u => u.BasketProducts.Where(b => !b.IsDeleted))
                .FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

            if (appUser.BasketProducts != null && appUser.BasketProducts.Any())
            {
                BasketProduct userBasketProduct = appUser.BasketProducts.FirstOrDefault(bp => bp.ProductId == id);
                if (userBasketProduct != null) userBasketProduct.Count = basketVMs.FirstOrDefault(b => b.Id == id).Count;
                else

Juan/JuanApp/Controllers/ProductController.cs
namespace JuanApp.Controllers;
public class ProductController : Controller
{
    private readonly AppDbContext _context;
    public ProductController(AppDbContext context) { _context = context; }

    public async Task<IActionResult> Index(int? id, int currentPage = 1)
    {
        IQueryable<Product> products = _context.Products
            .Where(p => !p.IsDeleted)
            .OrderByDescending(p => p.Id);
        
        if (id != null && await _context.Categories.AnyAsync(c => !c.IsDeleted && c.Id == id))
            products = products.Where(p => p.CategoryId == id);

        ShopVM shopVM = new()
        {
            Categories = await _context.Categories
            .Include(c => c.Products.Where(p => !p.IsDeleted))
            .Where(c => !c.IsDeleted).ToListAsync(),
            Products = PaginatedList<Product>.Create(products, currentPage, 6, 4)
        };

        return View(shopVM);
    }

    public async Task<IActionResult> CategoryFilter()
    {
        return View(nameof(Index));
    }

    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return BadRequest();

        Product? product = await _context.Products
            .Include(p => p.ProductImages.Where(pi => !pi.IsDeleted))
            .FirstOrDefaultAsync(p => !p.IsDeleted && p.Id == id);
        
        if (product == null) return NotFound();

        return View(product);
    }

    public async Task<IActionResult> Modal(int? id)
    {
        if (id == null) return BadRequest("Id cannot be null.");

        Product? product = await _context.Products
            .Include(p => p.ProductImages.Where(pi => !pi.IsDeleted))
            .FirstOrDefaultAsync(p => p.Id == id);

        if (product == null) return NotFound("Id is incorrect.");

        return PartialView("_ModalPartial", product);
    }

    public async Task<IActionResult> Search(string search, int? categoryId)
    {
        List<Product> products = new List<Product>();
        if (categoryId != null && await _context.Categories.AnyAsync(c => !c.IsDeleted && c.Id == categoryId))
        {
            products = await _context.Products
            .Where(p => !p.IsDeleted && (
            p.Title.ToLower().Contains(search.ToLower()) &&
            p.CategoryId == (int)categoryId)).ToListAsync();
        }
        else
        {
            products = await _context.Products
            .Where(p => !p.IsDeleted && (
            p.Category.Name.ToLower().Contains(search.ToLower()) ||
            p.Title.ToLower().Contains(search.ToLower()))).ToListAsync();
        }

        return PartialView("_SearchPartial", products);
    }
}

Juan/JuanApp/Views/Shared/Components/TopSeller/Default.cshtml
@model IEnumerable<Product>

<section class="top-seller-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title text-center">
                    <h2 class="title">top seller</h2>
                    <p class="sub-title">Lorem ipsum dolor sit amet consectetur adipisicing</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-5">
                <div class="product-banner">
                    <a asp-controller="Product" asp-action="Index">
                        <img src="~/assets/img/banner/banner-3.jpg" alt="product banner">
                    </a>
                </div>
            </div>
            <div class="col-xl-8 col-lg-7 col-md-7">
                <div class="top-seller-carousel slick-row-15 mtn-30">
                    @foreach (Product product in Model)
                    {
                        <div class="slide-item">
                            <div class="pro-item-small mt-30">
                                <div class="product-thumb">
                                    <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">
                                        <img src="~/assets/img/product/@product.MainImage" alt="">
                                    </a>
                                </div>
                                <div class="pro-small-content">
                                    <h6 class="product-name">
                                        <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">@product.Title</a>
                                    </h6>
                                    <div class="price-box">
                                        @if (product.Discount > 0)
                                        {
                                            <span class="price-regular">$@((product.Price * (100 - product.Discount) / 100).ToString("0.00"))</span>
                                            <span class="price-old"><del>$@product.Price.ToString("0.00")</del></span>
                                        }
                                        else { <span class="price-regular">$@product.Price.ToString("0.00")</span> }
                                    </div>
                                    <div class="ratings">
                                        <span><i class="ion-android-star"></i></span>
                                        <span><i class="ion-android-star"></i></span>
                                        <span><i class="ion-android-star"></i></span>
                                        <span><i class="ion-android-star"></i></span>
                                        <span><i class="ion-android-star"></i></span>
                                    </div>
                                    <div class="product-link-2">
                                        <a href="#" data-toggle="tooltip" title="Wishlist"><i class="ion-android-favorite-outline"></i></a>
                                        <a asp-controller="Basket" asp-action="AddBasket" asp-route-id="@product.Id" data-toggle="tooltip" title="Add To Cart"><i class="ion-bag"></i></a>
                                        <a asp-controller="Product" asp-action="Modal" asp-route-id="@product.Id" class="modal-btn" data-toggle="modal" data-target="#quick_view">
                                            <span data-toggle="tooltip" title="Quick View"><i class="ion-ios-eye-outline"></i></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>