Juan/JuanApp/Controllers/HomeController.cs
namespace JuanApp.Controllers;
public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Juan/JuanApp/ViewComponents/SliderViewComponent.cs
namespace JuanApp.ViewComponents;
public class SliderViewComponent : ViewComponent
{
    private readonly AppDbContext _context;
    public SliderViewComponent(AppDbContext context) { _context = context; }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        IEnumerable<Slider> sliders = await _context.Sliders.Where(s => !s.IsDeleted).ToListAsync();
        return View(sliders);
    }
}

Juan/JuanApp/Views/Home/Index.cshtml
<!-- hero slider section start -->
@await Component.InvokeAsync("Slider")
<!-- hero slider section end -->

<!-- service features start -->
<section class="service-policy-area">
    <div class="container">
        <div class="row">
            <!-- single policy item start -->
            <div class="col-lg-4">
                <div class="service-policy-item mt-30 bg-1">
                    <div class="policy-icon">
                        <img src="~/assets/img/icon/policy-1.png" alt="policy icon">
                    </div>
                    <div class="policy-content">
                        <h5 class="policy-title">FREE SHIPPING</h5>
                        <p class="policy-desc">Free shipping on all order</p>
                    </div>
                </div>
            </div>
            <!-- single policy item end -->

            <!-- single policy item start -->
            <div class="col-lg-4">
                <div class="service-policy-item mt-30 bg-2">
                    <div class="policy-icon">
                        <img src="~/assets/img/icon/policy-2.png" alt="policy icon">
                    </div>
                    <div class="policy-content">
                        <h5 class="policy-title">ONLINE SUPPORT</h5>
                        <p class="policy-desc">Online support 24 hours a day</p>
                    </div>
                </div>
            </div>
            <!-- single policy item end -->

            <!-- single policy item start -->
            <div class="col-lg-4">
                <div class="service-policy-item mt-30 bg-3">
                    <div class="policy-icon">
                        <img src="~/assets/img/icon/policy-3.png" alt="policy icon">
                    </div>
                    <div class="policy-content">
                        <h5 class="policy-title">MONEY RETURN</h5>
                        <p class="policy-desc">Back guarantee under 5 days</p>
                    </div>
                </div>
            </div>
            <!-- single policy item end -->
        </div>
    </div>
</section>
<!-- service features end -->

<!-- our product area start -->
@await Component.InvokeAsync("Featured")
<!-- our product area end -->

<!-- banner statistic area start -->
<div class="banner-statistics">
    <div class="container">
        <div class="row no-gutters mtn-30">
            <div class="col-md-6">
                <div class="img-container mt-30">
                    <a href="#">
                        <img src="~/assets/img/banner/banner-1.jpg" alt="banner-image">
                    </a>
                    <div class="banner-text">
                        <h5 class="banner-subtitle">sports shoes</h5>
                        <h3 class="banner-title">20% Off<br>For Sports men</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="img-container mt-30">
                    <a href="#">
                        <img src="~/assets/img/banner/banner-2.jpg" alt="banner-image">
                    </a>
                    <div class="banner-text">
                        <h5 class="banner-subtitle">sports shoes</h5>
                        <h3 class="banner-title">20% Off<br>For Sports men</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- banner statistic area end -->

<!-- top seller area start -->
@await Component.InvokeAsync("TopSeller")
<!-- top seller area end -->

<!-- latest blog area start -->
<section class="latest-blog-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title text-center">
                    <h2 class="title">our blog</h2>
                    <p class="sub-title">Lorem ipsum dolor sit amet consectetur adipisicing</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="blog-carousel-active slick-row-15">
                    <!-- blog single item start -->
                    <div class="blog-post-item">
                        <div class="blog-thumb">
                            <a href="blog-details.html">
                                <img src="~/assets/img/blog/blog-1.jpg" alt="blog thumb">
                            </a>
                        </div>
                        <div class="blog-content">
                            <h5 class="blog-title">
                                <a href="blog-details.html">
                                    Celebrity Daughter Opens About to Having Her Eye color
                                </a>
                            </h5>
                            <ul class="blog-meta">
                                <li><span>By: </span>Admin,</li>
                                <li><span>On: </span>14.07.2029</li>
                            </ul>
                            <a href="blog-details.html" class="read-more">Read More...</a>
                        </div>
                    </div>
                    <!-- blog single item end -->

                    <!-- blog single item start -->
                    <div class="blog-post-item">
                        <div class="blog-thumb">
                            <a href="blog-details.html">
                                <img src="~/assets/img/blog/blog-2.jpg" alt="blog thumb">
                            </a>
                        </div>
                        <div class="blog-content">
                            <h5 class="blog-title">
                                <a href="blog-details.html">
                                    Sotto Winner Offering Money To Any Man That Will Date Her
                                </a>
                            </h5>
                            <ul class="blog-meta">
                                <li><span>By: </span>Admin,</li>
                                <li><span>On: </span>14.07.2029</li>
                            </ul>
                            <a href="blog-details.html" class="read-more">Read More...</a>
                        </div>
                    </div>
                    <!-- blog single item end -->

                    <!-- blog single item start -->
                    <div class="blog-post-item">
                        <div class="blog-thumb">
                            <a href="blog-details.html">
                                <img src="~/assets/img/blog/blog-3.jpg" alt="blog thumb">
                            </a>
                        </div>
                        <div class="blog-content">
                            <h5 class="blog-title">
                                <a href="blog-details.html">
                                    Children Left Home Alone For 4 Days In TV Series Experiment
                                </a>
                            </h5>
                            <ul class="blog-meta">
                                <li><span>By: </span>Admin,</li>
                                <li><span>On: </span>14.07.2029</li>
                            </ul>
                            <a href="blog-details.html" class="read-more">Read More...</a>
                        </div>
                    </div>
                    <!-- blog single item end -->

                    <!-- blog single item start -->
                    <div class="blog-post-item">
                        <div class="blog-thumb">
                            <a href="blog-details.html">
                                <img src="~/assets/img/blog/blog-2.jpg" alt="blog thumb">
                            </a>
                        </div>
                        <div class="blog-content">
                            <h5 class="blog-title">
                                <a href="blog-details.html">
                                    People Are Willing Lie When To Comes Money Research from
                                </a>
                            </h5>
                            <ul class="blog-meta">
                                <li><span>By: </span>Admin,</li>
                                <li><span>On: </span>14.07.2029</li>
                            </ul>
                            <a href="blog-details.html" class="read-more">Read More...</a>
                        </div>
                    </div>
                    <!-- blog single item end -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- latest blog area end -->

<!-- brand area start -->
<div class="brand-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="brand-active-carousel">
                    <div class="brand-item">
                        <a href="#">
                            <img src="~/assets/img/brand/br1.png" alt="brand image">
                        </a>
                    </div>
                    <div class="brand-item">
                        <a href="#">
                            <img src="~/assets/img/brand/br2.png" alt="brand image">
                        </a>
                    </div>
                    <div class="brand-item">
                        <a href="#">
                            <img src="~/assets/img/brand/br3.png" alt="brand image">
                        </a>
                    </div>
                    <div class="brand-item">
                        <a href="#">
                            <img src="~/assets/img/brand/br4.png" alt="brand image">
                        </a>
                    </div>
                    <div class="brand-item">
                        <a href="#">
                            <img src="~/assets/img/brand/br5.png" alt="brand image">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- brand area end -->

<!-- Quick view modal start -->
<div class="modal" id="quick_view">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content"></div>
    </div>
</div>
<!-- Quick view modal end -->